package com.grocery.enums;

public enum ConfigKey {
    BASEURL,
    OVERRIDEREPORTS,
    RETRYFAILEDTEST,
    HOSTNAME,
    MAILAUTHENTICATOR,
    MAILPASSWORD,
    MANAGER,
    MANAGERNAME,
    MAILSUBJECT,
    MAILBODY,
    SETFROMMAIL,
    SETFROMNAME,
    SEND_RESULTS_TO_DASHBOARD,
    SEND_REPORTS_MAIL,
    DATA_SOURCE;
}
